# Generated by Django 5.0.7 on 2024-07-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
